### ISSUE TITLE
Style: Odds buttons

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bwx#16]
On the horse race page `http://localhost:3000/horses/xxx/n` make the place and win buttons the same width

![image](https://user-images.githubusercontent.com/8411406/138533411-684339d6-87f3-490d-9e4e-1626f2996878.png)

**Comment by yashsoni369** [comment]
Hi, can I take up this issue, also what is the max value going to be saved in `Win` and `Place` so we can set minimum width

![image](https://user-images.githubusercontent.com/37664594/138550257-9fd57abb-f358-4807-bc71-75345864eca2.png)

Above is the maximum 5 digit value assumption I made and set this layout, give your suggestions

**Comment by bitcoinbrisbane** [comment]
That looks great!  Make a PR?
