### ISSUE TITLE
Fix: Default to 50 rows

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bwx#20]
On mybets page, default to 50 rows on the table.

![image](https://user-images.githubusercontent.com/8411406/138545725-7935f11c-352b-4db1-a59b-4d82a86b3451.png)

**Comment by yashsoni369** [comment]
I am picking this, please assign it to me, also if you have any uat / dev / qa backend enviornment  if you can share for testing purpose, please revert on my mail Id

**Comment by bitcoinbrisbane** [comment]
> I am picking this, please assign it to me, also if you have any uat / dev / qa backend enviornment if you can share for testing purpose, please revert on my mail Id

Done!

**Comment by yashsoni369** [comment]
Do you have any api server for dev enviornment to test with real time data ?

**Comment by bitcoinbrisbane** [comment]
> Do you have any api server for dev enviornment to test with real time data ?

https://api.betwith.coins its live, but really a UAT

**Comment by yashsoni369** [comment]
perfect thanks
